name: dusterapp
description: 'Duster Buster App.'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  upgrader: ^11.3.1
  flutter_google_maps_webservices: ^1.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  uuid: ^4.5.1
  http: ^1.2.1
  flutter_secure_storage: ^9.2.4
  country_flags: ^3.2.0
  flutter_localization: ^0.3.1
  build_runner:
  flutter_gen_runner:
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  email_validator: ^3.0.0
  syncfusion_flutter_calendar: ^28.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
